version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: anytime
      MYSQL_USER: anytime
      MYSQL_PASSWORD: pestillo
      MYSQL_ROOT_PASSWORD: pestillo

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
  server:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "./server:/usr/anytime/server"
  client:
    image: nginx
    restart: always
    ports:
      - "3000:80"
    volumes:
      - "./client:/usr/share/nginx/html"
