version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: anytime
      MYSQL_USER: anytime
      MYSQL_PASSWORD: pestillo
      MYSQL_ROOT_PASSWORD: pestillo

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1

  server:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    volumes:
      - "./server:/usr/anytime/server"
    command: java -jar anytime.jar

  client:
    image: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - "server"
    volumes:
      - "./client:/usr/share/nginx/html"
